from typing import Final

RAW_TABLE_CONTRACTS: dict[str, list[str]] = {
    "raw.customers": [
        "customer_id",
        "customer_unique_id",
        "customer_zip_code_prefix",
        "customer_city",
        "customer_state",
    ],
    "raw.orders": [
        "order_id",
        "customer_id",
        "order_status",
        "order_purchase_timestamp",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date",
        "order_estimated_delivery_date",
    ],
    "raw.order_items": [
        "order_id",
        "order_item_id",
        "product_id",
        "seller_id",
        "shipping_limit_date",
        "price",
        "freight_value",
    ],
    "raw.order_payments": [
        "order_id",
        "payment_sequential",
        "payment_type",
        "payment_installments",
        "payment_value",
    ],
    "raw.products": [
        "product_id",
        "product_category_name",
        "product_name_lenght",
        "product_description_lenght",
        "product_photos_qty",
        "product_weight_g",
        "product_length_cm",
        "product_height_cm",
        "product_width_cm",
    ],
}


ANALYTICS_TABLE_CONTRACTS: dict[str, list[str]] = {
    "analytics.order_metrics": [
        "order_id",
        "customer_id",
        "order_status",
        "order_purchase_timestamp",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date",
        "order_estimated_delivery_date",
        "total_items",
        "product_value",
        "freight_value",
        "payment_value",
    ],
    "analytics.customer_metrics": [
        "customer_unique_id",
        "total_orders",
        "total_items",
        "total_spent",
        "average_order_value",
        "first_order_date",
        "last_order_date",
        "customer_lifetime_days",
    ],
    "analytics.customer_rfm": [
        "customer_unique_id",
        "recency",
        "frequency",
        "monetary",
        "recency_score",
        "frequency_score",
        "monetary_score",
        "rfm_score",
        "segment",
    ],
}

RAW_COLUMN_TYPES: Final[dict[str, dict[str, str]]] = {
    "customers": {
        "customer_id": "VARCHAR",
        "customer_unique_id": "VARCHAR",
        "customer_zip_code_prefix": "VARCHAR",
        "customer_city": "VARCHAR",
        "customer_state": "VARCHAR",
    },
    "orders": {
        "order_id": "VARCHAR",
        "customer_id": "VARCHAR",
        "order_status": "VARCHAR",
        "order_purchase_timestamp": "TIMESTAMP",
        "order_approved_at": "TIMESTAMP",
        "order_delivered_carrier_date": "TIMESTAMP",
        "order_delivered_customer_date": "TIMESTAMP",
        "order_estimated_delivery_date": "TIMESTAMP",
    },
    "order_items": {
        "order_id": "VARCHAR",
        "order_item_id": "BIGINT",
        "product_id": "VARCHAR",
        "seller_id": "VARCHAR",
        "shipping_limit_date": "TIMESTAMP",
        "price": "DOUBLE",
        "freight_value": "DOUBLE",
    },
    "order_payments": {
        "order_id": "VARCHAR",
        "payment_sequential": "BIGINT",
        "payment_type": "VARCHAR",
        "payment_installments": "BIGINT",
        "payment_value": "DOUBLE",
    },
    "products": {
        "product_id": "VARCHAR",
        "product_category_name": "VARCHAR",
        "product_name_lenght": "BIGINT",
        "product_description_lenght": "BIGINT",
        "product_photos_qty": "BIGINT",
        "product_weight_g": "BIGINT",
        "product_length_cm": "BIGINT",
        "product_height_cm": "BIGINT",
        "product_width_cm": "BIGINT",
    },
}


ANALYTICS_COLUMN_TYPES: Final[dict[str, dict[str, str]]] = {
    "order_metrics": {
        "order_id": "VARCHAR",
        "customer_id": "VARCHAR",
        "order_status": "VARCHAR",
        "order_purchase_timestamp": "TIMESTAMP",
        "order_approved_at": "TIMESTAMP",
        "order_delivered_carrier_date": "TIMESTAMP",
        "order_delivered_customer_date": "TIMESTAMP",
        "order_estimated_delivery_date": "TIMESTAMP",
        "total_items": "BIGINT",
        "product_value": "DOUBLE",
        "freight_value": "DOUBLE",
        "payment_value": "DOUBLE",
    },
    "customer_metrics": {
        "customer_unique_id": "VARCHAR",
        "total_orders": "BIGINT",
        "total_items": "HUGEINT",
        "total_spent": "DOUBLE",
        "average_order_value": "DOUBLE",
        "first_order_date": "TIMESTAMP",
        "last_order_date": "TIMESTAMP",
        "customer_lifetime_days": "BIGINT",
    },
    "customer_rfm": {
        "customer_unique_id": "VARCHAR",
        "recency": "BIGINT",
        "frequency": "BIGINT",
        "monetary": "DOUBLE",
        "recency_score": "BIGINT",
        "frequency_score": "BIGINT",
        "monetary_score": "BIGINT",
        "rfm_score": "BIGINT",
        "segment": "VARCHAR",
    },
}
